on: workflow_dispatch
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Action Doxygen and GitHub Pages
        id: ghaction
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          doxyfile-path: ${{github.workspace}}/Doxyfile.in
          html-output-folder: ${{github.workspace}}/docs
          branch: gh-pages
