on: workflow_dispatch
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set git config email
        id: set-git-config-email
        run: echo "git-config-email=ismael.correa.castro@gmail.com" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Action Doxygen and GitHub Pages
        id: ghaction
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.DOXYGEN_SECRET }}
          working-directory: .
          doxyfile-path: ./Doxyfile
          html-output-folder: ./docs
          branch: gh-pages
          target_folder: docs
